### ISSUE TITLE
Video and Audio media

### ISSUE THREAD

**Issue by t8n** [newzealandpaul/webarchiver#10]
Is it possible for video and audio to be included in a webarchive? I've created a simple bit of html that opens fine in a browser, but the webarchive doesn't include the files (works with images though). Is this a limitation of WebView?

```html
<html><body>

<h2>Video Test</h2>
<p><video controls="" name="media" style="max-width: 100%; max-height: 100%;"><source src="TestVideo.mp4" type="video/mp4"></video>
Another way?
<embed src="TestVideo.mp4" width="100%" autostart="false" loop="FALSE"></embed>
</p>
<h2>Audio Test</h2>
<p><audio controls preload="auto">
    <source src="horse.mp3" type="audio/mp3">
</audio>
</p>
</body>
</html>
```

**Comment by newzealandpaul** [comment]
Looks to do a webview issue unfortunately, so I won't be able to fix it, sorry.
