### ISSUE TITLE
support for some URI valid chars

### ISSUE THREAD

**Issue by fabthecop** [newzealandpaul/webarchiver#11]
I'm using it with the BREW (OSX) version, not mentioned in the documentation.
It seems it doesn't support urls with percent ASCII encoding.

**E.g.**
https://www.***.com/Information%20Security%20Governance/1.005_Check/index.html

**Returns:**
Error: Unable to create webarchive
Error Domain=KBWebArchiverErrorDomain
Code=1 "Invalid URL" UserInfo={NSLocalizedDescription=Invalid URL,
NSLocalizedRecoverySuggestion=The URL was invalid and so could not be converted to a web archive.}

A deeper inspection to the source and in particular NSURL+ValidityChecking.m raises a check on HTTP response (200 is needed). This is not related to the URL, resulting that the message "The URL was invalid" is misleading. In addition, the check for HTTP 200 can't be considered safe, since nowadays a lot of different responses, redirects, JS codes, sessions and cookies, etc actually lead to a good webpage. IMHO the check can be removed also for future benefit, since any issue can be seen directly in the webarchive itself.

**Comment by mark1bean** [comment]
I had a similar experience, and removing the check on HTTP response 200 fixed it. Here's [an example URL](https://www.shannons.com.au/auctions/2020-shannons-winter-timed-online-auction/X28EZDS5N7F1MCY/) that failed before removing the check and makes a perfect .webarchive after removing it.

**Comment by newzealandpaul** [comment]
I am happy to merge in a fix if anyone can write one.

**Comment by newzealandpaul** [comment]
Closing
