### ISSUE TITLE
Homebrew disabled due to no license

### ISSUE THREAD

**Issue by webbsledge** [newzealandpaul/webarchiver#15]
Homebrew has disabled Webarchiver due to its lack of a license included in the repository. This should be quite an easy fix, if the author cares to select a license that meets the Debian Free Software Guidelines criteria.

[Homebrew License Guidelines](https://docs.brew.sh/License-Guidelines)

[DFSG License Wiki](https://wiki.debian.org/DFSGLicenses)

**Comment by newzealandpaul** [comment]
@webbsledge the license has been added as required. Are you able to get it reenabled in homebrew?

**Comment by webbsledge** [comment]
@newzealandpaul I don't think I have that power. I don't have experience creating home-brew formulae, but it appears you'll need to create a fork of the homebrew repo and submit a PR, as outlined in the Homebrew documentation:

[Adding Software to Homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew)

[How to Open a Homebrew Pull Request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#formulae-related-pull-request)

**Comment by newzealandpaul** [comment]
I have commented on this commit:

https://github.com/Homebrew/homebrew-core/commit/b4a2c24d38699c04c95174465f199e26d97c8f7e

I believe I have fulfilled the requirements for it to be re-enabled.

**Comment by webbsledge** [comment]
Great! I will look for its re-enabling in brew, and look forward to using it!

**Comment by newzealandpaul** [comment]
I have submitted a pull request to homebrew-core

https://github.com/Homebrew/homebrew-core/pull/182917

**Comment by newzealandpaul** [comment]
Webarchiver has been re-enabled in Homebrew 💯
