### ISSUE TITLE
Not working as expected.

### ISSUE THREAD

**Issue by openingnow** [newzealandpaul/webarchiver#9]
I tried `webarchiver -url http://www.webtoons.com/en/fantasy/the-gamer/season-2-ep-26/viewer?title_no=88&episode_no=113 -output asdasd.webarchive` but failed with error:
```
[1] 28847
-bash: -output: command not found
```
As I tested google.com, it works fine except the site looks like if javascript was disabled.

What should I do to archive such sites?

**Comment by newzealandpaul** [comment]
You need to put the url in quote marks. This is just now bash (command line) works.

webarchiver -url **"**http://www.webtoons.com/en/fantasy/the-gamer/season-2-ep-26/viewer?title_no=88&episode_no=113**"** -output asdasd.webarchive

**Comment by openingnow** [comment]
Wow, thanks for very quick answer!
